name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Ajusta la rama de despliegue según sea necesario

permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: jamesgeorge007/github-pages-deploy-action@v4.2.0
        with:
          branch: gh-pages  # Usamos la rama gh-pages para el despliegue
          folder: dist  # La carpeta que contiene los archivos generados
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Usar el token de acceso como secreto
